export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const LOGIN_IN_DOING = 'LOGIN_IN_DOING';
export const LOGIN_IN_DONE = 'LOGIN_IN_DONE';
export const LOGIN_IN_ERROR = 'LOGIN_IN_ERROR';

export const PORTRAIT = 'PORTRAIT';
export const LANDSCAPE = 'LANDSCAPE';

export const SHOW_MESSAGEMODAL = 'SHOW_MESSAGEMODAL';
export const CLOSE_MESSAGEMODAL = 'CLOSE_MESSAGEMODAL';

export const SET_MESSAGESTR = 'SET_MESSAGESTR';
export const SET_MESSAGEMEDIA = 'SET_MESSAGEMEDIA';

export const SENDING_MESSAGE = 'SENDING_MESSAGE'
export const SEND_SUCCESS = 'SEND_SUCCESS'
export const SEND_ERROR = 'SEND_ERROR'

export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE'
export const REMOVE_CHAT_MESSAGE = 'REMOVE_CHAT_MESSAGE'
export const SET_REFRESH_STATUS = 'SET_REFRESH_STATUS'
export const GO_TO_END = 'GO_TO_END'


